version: '3.8'

services:
  app:
    build: 
      context: app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app/src:/src
    environment:
      - RELOAD=true
    env_file:
      - .env
  
  cronjobs:
    build:
      context: cronjobs
      dockerfile: Dockerfile
    volumes:
      - ./cronjobs/src:/src
    environment:
      - RELOAD=true
    env_file:
      - .env
    depends_on:
      - app